name: aerovod
on:
  push:
  schedule:
    - cron: "0 */72 * * *"  # every three days
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1.1.1
    - run: pip install -r requirements.txt
    - run: python ./scripts/aerovod.py > ./film2trello/aerovod.json
    - uses: EndBug/add-and-commit@v4.0.1
      with:
        add: ./aerovod/films.json
        author_name: "GitHub Actions"
        message: "update the list of films available at Aerovod"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
